name: Report a Bug or Problem
description: "Create a report to help me fix the issue you've encountered"
labels: ["issue"]
title: "[ISSUE]: "
body:
  - type: dropdown
    id: server-only-issue
    attributes:
      label: Where did you encounter this issue?
      options:
        - "Singleplayer"
        - "As Server Host"
        - Unsure or Neither
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod Version
      description: What version of the mod is installed?
      placeholder: e.g. 1.3.6
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you playing?
      placeholder: e.g. 1.21.4
    validations:
      required: true
  - type: dropdown
    id: mod-loader
    attributes:
      label: Minecraft Mod Loader
      description: What Mod loader are you using?
      options:
        - Fabric
        - Other (Please specify below!)
    validations:
      required: true
  - type: input
    id: mod-loader-version
    attributes:
      label: Mod Loader Version
      description: What Mod Loader Version are you running? (If it isn't Fabric specify which Mod Loader you're using.)
      placeholder: e.g. 0.16.10
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Try to describe problem you're running into and if applicable, what you would expect to happen instead.
      placeholder: e.g. When I do X, Y happens instead of Z.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide a short summary of what steps need to happen for this issue to occur.
      placeholder: |
        1. Be in Situation X.
        2. Try to do Action Y.
        3. The game crashes. :(
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: Upload the crash report (or the _latest.log_) to this site and send the link here - https://mclo.gs/
      placeholder: https://mclo.gs/....
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please review the following checklist before submitting your issue.
      options:
        - label: I have searched both open and closed issues for similar issues and I couldn't find anything.
          required: true
