name: publish-datapack

on:
  workflow_call:
    secrets:
      MODRINTH_TOKEN:
        description: 'The token to use for Modrinth authentication'
        required: true
      CURSEFORGE_TOKEN:
        description: 'The token to use for Curseforge authentication'
        required: true
    inputs:
      default-branch:
        type: string
        description: 'The default branch to be referenced for changelog history links'
        required: false
        default: '1.21(.1)'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: ./.github/actions/prepare-changelog
        with:
          default-branch: ${{ inputs.default-branch }}

      - name: check necessary files for packing (data dir, pack.mcmeta, pack.png, pack.properties)
        run: |
          set -e
          if [[ ! -d data ]]; then
            echo "Missing data directory"
            exit 1
          fi
          if [[ ! -f pack.mcmeta ]]; then
            echo "Missing pack.mcmeta"
            exit 1
          fi
          if [[ ! -f pack.png ]]; then
            echo "Missing pack.png"
            exit 1
          fi
          if [[ ! -f pack.properties ]]; then
            echo "Missing pack.properties"
            exit 1
          fi
        continue-on-error: false

      - name: read metadata from pack.properties
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './pack.properties'
          properties: 'archives_base_name pack_name pack_version minecraft_version_supported minecraft_version_filter minecraft_version_name modrinth_id curseforge_id dependencies'

      - name: format version name and title
        id: format_version_name
        run: |
          archives_base_name="${{ steps.properties.outputs.archives_base_name }}"
          escaped_version_name=$(echo "${{ steps.properties.outputs.minecraft_version_name }}" | sed 's/(/\\(/g; s/)/\\)/g')
          echo "escaped_version_name=$escaped_version_name" >> "$GITHUB_OUTPUT"
          pack_version_number="${{ steps.properties.outputs.pack_version }} + ${{ steps.properties.outputs.minecraft_version_name }}"
          mr_version_title="${{ steps.properties.outputs.pack_name }} $pack_version_number"
          cf_version_title="$pack_version_number - ${{ steps.properties.outputs.pack_name }}"
          file_path_glob="out/${{ steps.properties.outputs.archives_base_name }}-${{ steps.properties.outputs.mod_version }}+$escaped_version_name.zip"
          echo "archives_base_name=$archives_base_name" >> "$GITHUB_OUTPUT"
          echo "pack_version_number=$pack_version_number" >> "$GITHUB_OUTPUT"
          echo "mr_version_title=$mr_version_title" >> "$GITHUB_OUTPUT"
          echo "cf_version_title=$cf_version_title" >> "$GITHUB_OUTPUT"
          echo "file_path_glob=$file_path_glob" >> "$GITHUB_OUTPUT"

      - name: build datapack zip
        run: |
          set -e
          mkdir -p out
          zip -r "out/${{ steps.properties.outputs.archives_base_name }}-${{ steps.properties.outputs.mod_version }}+${{ steps.properties.outputs.minecraft_version_name }}.zip" data pack.mcmeta pack.png
        continue-on-error: false

      - uses: Kir-Antipov/mc-publish@v3.3
        id: publish-mr
        with:
          modrinth-id: '${{ steps.properties.outputs.modrinth_id }}'
          modrinth-featured: true
          modrinth-unfeature-mode: intersection
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          name: '${{ steps.format_version_name.outputs.mr_version_title }}'
          version: '${{ steps.properties.outputs.mod_version }}'

          game-versions: '${{ steps.properties.outputs.minecraft_version_supported }}'
          game-version-filter: '${{ steps.properties.outputs.minecraft_version_filter }}'

          loaders: |
            datapack
            fabric
            neoforge
            quilt

          dependencies: '${{ steps.properties.outputs.dependencies }}'

          version-type: release
          files: "${{ steps.format_version_name.outputs.file_path_glob }}"

          changelog-file: CHANGELOG.md

      - uses: Kir-Antipov/mc-publish@v3.3
        id: publish-cf
        with:
          curseforge-id: '${{ steps.properties.outputs.curseforge_id }}'
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          name: '${{ steps.format_version_name.outputs.cf_version_title }}'
          version: '${{ steps.properties.outputs.mod_version }}'

          game-versions: '${{ steps.properties.outputs.minecraft_version_supported }}'
          game-version-filter: '${{ steps.properties.outputs.minecraft_version_filter }}'

          loaders: |
            datapack

          dependencies: '${{ steps.properties.outputs.dependencies }}'

          version-type: release
          files: "${{ steps.format_version_name.outputs.file_path_glob }}"

          changelog-file: CHANGELOG_cf.md
          retry-delay: 2000
          retry-attempts: 1
          fail-mode: warn
        continue-on-error: true

      - uses: ./.github/actions/publish-changelog
        with:
          version: ${{ steps.properties.outputs.mod_version }}
          modrinth-id: ${{ steps.publish-mr.outputs.modrinth-id }}
          modrinth-version: ${{ steps.publish-mr.outputs.modrinth-version }}
          curseforge-url: ${{ steps.publish-cf.outputs.curseforge-url }}
          version-number: ${{ steps.format_version_name.outputs.pack_version_number }}
          mr-version-title: ${{ steps.format_version_name.outputs.mr_version_title }}
          cf-version-title: ${{ steps.format_version_name.outputs.cf_version_title }}
